### ISSUE TITLE
improve the k-a versioning in the test-infra kubeadm runner

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubernetes-anywhere#555]
we eventually want to deprecate kubernetes-anywhere in the e2e suite.
but this isn't that easy, so we have to stick to it for a while.

right now we have a fixed k-a (kuberenetes-anywhere) commit in the image for the kubeadm runner.
this imposes the difficulty that we need to PR two changes:
- one that fixes k-a
- one that updates the SHA in `runner`.

https://github.com/neolit123/test-infra/blob/8f0bd23ac99e7c8809ccc6aefb42273dc96ca066/images/kubeadm/runner#L29

my proposal:
- create a k-a branch called `kubeadm-runner` in this repo
- push e2e related changes and fixes to this branch.
- **always** use the tip of the branch `kubeadm-runner` in the runner!!
- cherry pick changes from the `kubeadm-runner` branch to the k-a master branch if needed.

future changes in kubeadm are going to make k-a very hard to maintain for both users and e2e tests.

/assign @timothysc 
/assign @BenTheElder 
/priority critical-urgent
/kind feature

/cc @errordeveloper @luxas @mikedanese 
for super powers on creating a k-a branch called `kubeadm-runner` if this is approved by @BenTheElder and @timothysc

**Comment by BenTheElder** [comment]
All we need is some way to note the stable version to use for CI. I'm open to anything...

I think if we do keep the version specified at the test-config we should remove this checkout from the runner and instead specify it with --repo on the kubeadm jobs. This will update when the PR merges instead of after upgrading the images, and it potentially lets us freeze the version for older kubernetes releases.

**Comment by neolit123** [comment]
i see a `--repo` argument already present here:
https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-cluster-lifecycle/kubeadm.yaml

but it points to the main repo.

there is this check:
https://github.com/neolit123/test-infra/blob/8f0bd23ac99e7c8809ccc6aefb42273dc96ca066/images/kubeadm/runner#L24

if we remove it and always checkout a fresh copy of a stable k-a branch wouldn't this image work when the periodics trigger without updating the images everytime?

i must admit that i don't understand how it all works.

the idea of the `kubeadm-runner` branch is to also move the e2e work outside of the k-a `master` because:
> future changes in kubeadm are going to make k-a very hard to maintain for both users and e2e tests.

**Comment by BenTheElder** [comment]
> i see a --repo argument already present here: ...

Yes, you can supply multiple repos, the first one will be $PWD for testing, but the others will be checked out along side it as well, and you can specify a hash for those. We can remove the checkout from the runner and instead specify which release to checkout on each job as an extra repo, which also makes it configurable per-job / per-kubernetes-release

**Comment by neolit123** [comment]
if we hardcode the hash or release (is it a [k-a release](https://github.com/kubernetes/kubernetes-anywhere/releases)?) in the job config, wouldn't that mean that if we bump k-a by one patch/fix/commit we still need to update the job config too and possibly make a new k-a release?

is it possible to specify a branch (tip) instead?
and know that this removes the "stable" / release factor from k-a.

**Comment by BenTheElder** [comment]
> if we hardcode the hash or release (is it a k-a release?) in the job config, wouldn't that mean that if we bump k-a by one patch/fix/commit we still need to update the job config too 

We can do that though, and selectively for the tests that actually need it (probably just recent k/k branches)

> and possibly make a new k-a release?

does k-a have releases?

> is it possible to specify a branch (tip) instead?

yep you can just specify a branch without a sha. independently of what way we specify the stable version (sha, branch, ...) we should probably move specifying it to be on the jobs so updates to this are quick (and likely only involve cluster-lifecycle to review & merge), versus needing a new image to be published first.

**Comment by neolit123** [comment]
> We can do that though, and selectively for the tests that actually need it (probably just recent k/k branches)

ok, given right now we always use the tip of k-a, all tests are conformant with the tip of k-a.

ideally the tests by default should use the latest (presumably patched branch tip), but if a test complains we can specify an exact commit.

> does k-a have releases?

it has one...
the project is quite inactive in terms of maintenance and it appears we only use it for e2e.
it does have some user base, but i'm considering sending a README.md update to note about the above.

and eventually in time deprecating it for e2e.

> yep you can just specify a branch without a sha. independently of what way we specify the stable version (sha, branch, ...) we should probably move specifying it to be on the jobs so updates to this are quick (and likely only involve cluster-lifecycle to review & merge), versus needing a new image to be published first.

would that be a valid diff?
```
- name: ci-kubernetes-e2e-kubeadm-gce-selfhosting
  interval: 6h
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - image: gcr.io/k8s-testimages/e2e-kubeadm:v20180730-c8036c3a7
      args:
      - --repo=k8s.io/kubernetes=master
      - --timeout=320
      - --upload=gs://kubernetes-jenkins/logs
      - --scenario=kubernetes_e2e
      - --
      - --cluster=
      - --deployment=kubernetes-anywhere
      - --extract=ci/latest-bazel
      - --gcp-zone=us-central1-f
      - --kubeadm=ci
+     - --repo=k8s.io/kubernetes-anywhere=<some-branch>
      - --kubernetes-anywhere-kubeadm-feature-gates=SelfHosting=true
      - --kubernetes-anywhere-kubelet-ci-version=latest-bazel
      - --kubernetes-anywhere-kubernetes-version=ci-cross/latest
      - --provider=kubernetes-anywhere
      - --test_args=--ginkgo.focus=\[Conformance\]|\[Feature:BootstrapTokens\]|\[Feature:NodeAuthorizer\] --minStartupPods=8
      - --timeout=300m
```

would that replace the checkout in the runner?
